"""Materialize local Markdown memory views from cluster records."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from observational_memory.config import Config
from observational_memory.startup_memory import refresh_startup_memory

from .atomic import DirectoryLock, atomic_write_text
from .frontier import frontier_covers, frontier_from_records
from .records import RecordEnvelope
from .store import ClusterStore

GENERATED_HEADER = (
    "<!-- Generated by Observational Memory Cluster. Do not edit directly. -->\n"
    "<!-- To make durable manual changes, use cluster overrides or disable cluster materialization. -->\n\n"
)


@dataclass(frozen=True)
class MaterializeSummary:
    observations_written: bool
    reflections_written: bool
    profile_written: bool
    active_written: bool
    catchup_needed: bool = False

    @property
    def any_written(self) -> bool:
        return self.observations_written or self.reflections_written or self.profile_written or self.active_written


def materialize_cluster_memory(config: Config, store: ClusterStore, *, reindex: bool = True) -> MaterializeSummary:
    store.ensure_layout()
    with DirectoryLock(store.cluster_dir / ".locks" / "materialize.lock"):
        observations = _render_observations(config, store)
        observations_written = _write_if_changed(config.observations_path, observations)

        reflections, catchup_needed = _render_reflections(store)
        reflections_written = False
        if reflections is not None:
            reflections_written = _write_if_changed(config.reflections_path, reflections)

        refresh_startup_memory(config)
        profile_written = _prepend_generated_header(config.profile_path)
        active_written = _prepend_generated_header(config.active_path)
        profile_written = _apply_overrides(config.profile_path, store, "profile") or profile_written
        active_written = _apply_overrides(config.active_path, store, "active") or active_written

        summary = MaterializeSummary(
            observations_written=observations_written,
            reflections_written=reflections_written,
            profile_written=profile_written,
            active_written=active_written,
            catchup_needed=catchup_needed,
        )
        if reindex and summary.any_written:
            _reindex_if_enabled(config)
        return summary


def choose_reflection_snapshot(store: ClusterStore) -> tuple[RecordEnvelope | None, bool]:
    snapshots = store.list_records(kind="reflection_snapshot")
    if not snapshots:
        return None, bool(store.list_records(kind="observation"))

    def snapshot_key(record: RecordEnvelope) -> tuple[int, str, str]:
        try:
            frontier = store.read_payload(record).get("frontier", {})
        except Exception:
            frontier = {}
        total = sum(int(v) for v in frontier.values() if isinstance(v, int))
        return total, record.hlc, record.record_id

    selected = max(snapshots, key=snapshot_key)
    try:
        selected_frontier = store.read_payload(selected).get("frontier", {})
    except Exception:
        selected_frontier = {}
    observations_frontier = frontier_from_records(store.list_records(kind="observation"))
    catchup_needed = not frontier_covers(selected_frontier, observations_frontier)
    return selected, catchup_needed


def _render_observations(config: Config, store: ClusterStore) -> str:
    cutoff = datetime.now(timezone.utc) - timedelta(days=config.observation_retention_days)
    sections: list[tuple[str, str, RecordEnvelope, dict[str, Any]]] = []
    for record in store.list_records(kind="observation"):
        payload = store.read_payload(record)
        observed_at = str(payload.get("observed_at") or record.hlc[:10])
        date = observed_at[:10]
        if _parse_date(date) and _parse_date(date) < cutoff.date():
            continue
        sections.append((date, record.hlc, record, payload))
    sections.sort(key=lambda row: (row[0], row[1], row[2].node_id, row[2].node_seq, row[2].record_id))

    lines = [
        "# Observations",
        "",
        GENERATED_HEADER.rstrip(),
    ]
    current_date = None
    for date, _hlc, record, payload in sections:
        if date != current_date:
            lines.extend(["", f"## {date}", ""])
            current_date = date
        source = record.data.get("source", {})
        label_parts = [
            str(source.get("host_alias") or record.node_id),
            str(source.get("agent") or "unknown"),
        ]
        if source.get("project"):
            label_parts.append(f"project:{source['project']}")
        label_parts.append(record.namespace)
        lines.append(f"### From {' / '.join(label_parts)}")
        lines.append("")
        body = _strip_observation_wrapper(str(payload.get("body", ""))).strip()
        if body:
            lines.append(body)
        lines.append("")
        lines.append(f"<!-- record: {record.record_id} seq:{record.node_id}:{record.node_seq} -->")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_reflections(store: ClusterStore) -> tuple[str | None, bool]:
    selected, catchup_needed = choose_reflection_snapshot(store)
    if selected is None:
        return None, catchup_needed
    payload = store.read_payload(selected)
    body = str(payload.get("body", "")).strip()
    if not body:
        return None, catchup_needed
    note = "\n\n<!-- Cluster reflection catch-up needed: local observations exceed selected snapshot frontier. -->"
    return GENERATED_HEADER + body + (note if catchup_needed else "") + "\n", catchup_needed


def _apply_overrides(path: Path, store: ClusterStore, target: str) -> bool:
    overrides: list[tuple[str, str, RecordEnvelope]] = []
    for record in store.list_records(kind="manual_override"):
        payload = store.read_payload(record)
        if payload.get("target") != target:
            continue
        section = str(payload.get("section") or "general")
        body = str(payload.get("body") or "").strip()
        if body:
            overrides.append((section, body, record))
    if not overrides:
        return False
    existing = path.read_text() if path.exists() else ""
    marker = "\n## Manual Overrides\n"
    base = existing.split(marker, 1)[0].rstrip()
    lines = [base, marker.strip(), ""]
    seen: set[tuple[str, str]] = set()
    for section, body, record in sorted(overrides, key=lambda row: (row[0], row[2].hlc, row[2].record_id)):
        key = (section, body)
        if key in seen:
            continue
        seen.add(key)
        lines.extend([f"### {section}", "", body, "", f"<!-- override-record: {record.record_id} -->", ""])
    return _write_if_changed(path, "\n".join(lines).rstrip() + "\n")


def _prepend_generated_header(path: Path) -> bool:
    existing = path.read_text() if path.exists() else ""
    if existing.startswith(GENERATED_HEADER):
        return False
    return _write_if_changed(path, GENERATED_HEADER + existing)


def _write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text() == content:
        return False
    atomic_write_text(path, content)
    return True


def _strip_observation_wrapper(body: str) -> str:
    body = re.sub(r"(?m)^# Observations\s*", "", body).strip()
    body = re.sub(r"(?m)^## \d{4}-\d{2}-\d{2}\s*", "", body).strip()
    return body


def _parse_date(value: str):
    try:
        return datetime.strptime(value, "%Y-%m-%d").date()
    except ValueError:
        return None


def _reindex_if_enabled(config: Config) -> None:
    if config.search_backend == "none":
        return
    try:
        from observational_memory.search import reindex

        reindex(config)
    except Exception:
        pass
