import json
from datetime import datetime, timezone

from observational_memory.config import Config
from observational_memory.sync.config import (
    TransportConfig,
    create_invite_token,
    initialize_cluster_config,
    join_cluster_from_invite,
)
from observational_memory.sync.materialize import materialize_cluster_memory
from observational_memory.sync.store import ClusterStore


def _init_store(tmp_path, name="Test", alias="node-a"):
    config = Config(memory_dir=tmp_path / alias / "memory", env_file=tmp_path / alias / "config" / "env")
    cluster_config = initialize_cluster_config(
        config,
        name=name,
        node_alias=alias,
        transports=[TransportConfig(type="filesystem", path=str(tmp_path / "shared"))],
    )
    store = ClusterStore.from_config(config)
    store.ensure_layout()
    store.append_record(
        kind="node_membership",
        namespace=cluster_config.default_namespace,
        source={"agent": "test"},
        payload={
            "operation": "add",
            "node_id": cluster_config.node_id,
            "alias": cluster_config.node_alias,
            "signing_public_key": store.keypair.signing_public_key_b64,
            "created_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        },
    )
    return config, store


def test_append_read_heads_permissions_and_no_plaintext(tmp_path):
    config, store = _init_store(tmp_path)

    record = store.append_record(
        kind="observation",
        namespace="personal",
        source={"agent": "codex", "host_alias": "node-a"},
        payload={"format": "markdown", "body": "- top secret", "observed_at": "2026-05-08T12:00:00Z"},
    )

    assert store.read_payload(record)["body"] == "- top secret"
    assert store.all_heads()[store.cluster_config.node_id] == 2
    record_file = next((config.clusters_dir / store.cluster_config.id / "records").glob("*/*.omr.json"))
    assert b"top secret" not in record_file.read_bytes()
    assert oct((config.cluster_keys_dir / store.cluster_config.id / "node.json").stat().st_mode & 0o777) == "0o600"
    assert oct((config.cluster_keys_dir / store.cluster_config.id / "cluster.key").stat().st_mode & 0o777) == "0o600"


def test_duplicate_import_is_idempotent_and_tamper_rejected(tmp_path):
    config_a, store_a = _init_store(tmp_path, alias="node-a")
    invite_token = create_invite_token(config_a, store_a.cluster_config, expires="1h")
    config_b = Config(memory_dir=tmp_path / "node-b" / "memory", env_file=tmp_path / "node-b" / "config" / "env")
    join_cluster_from_invite(config_b, invite_token, node_alias="node-b")
    store_b = ClusterStore.from_config(config_b)
    store_b.ensure_layout()
    record = store_a.append_record(
        kind="observation",
        namespace="personal",
        source={"agent": "codex"},
        payload={"format": "markdown", "body": "- shared", "observed_at": "2026-05-08T12:00:00Z"},
    )

    first = store_b.import_record_bytes(record.to_bytes())
    second = store_b.import_record_bytes(record.to_bytes())
    assert first.imported
    assert second.status == "duplicate"

    tampered = json.loads(record.to_bytes())
    tampered["source"]["agent"] = "evil"
    rejected = store_b.import_record_bytes(json.dumps(tampered).encode("utf-8"))
    assert rejected.status == "rejected"


def test_materialize_observations_reflections_redactions_and_overrides(tmp_path):
    config, store = _init_store(tmp_path)
    observation = store.append_record(
        kind="observation",
        namespace="personal",
        source={"agent": "codex", "host_alias": "node-a", "project": "om"},
        payload={
            "format": "markdown",
            "body": "# Observations\n\n## 2026-05-08\n\n- hello cluster",
            "observed_at": "2026-05-08T12:00:00Z",
        },
    )
    store.append_record(
        kind="reflection_snapshot",
        namespace="personal",
        source={"agent": "reflector"},
        payload={
            "format": "markdown",
            "body": (
                "# Reflections\n\n"
                "*Last updated: 2026-05-08 12:00 UTC*\n"
                "*Last reflected: 2026-05-08*\n\n"
                "## Core Identity\n- Test"
            ),
            "frontier": store.records_frontier(),
            "input_record_ids": [observation.record_id],
            "base_snapshot_ids": [],
        },
    )
    override = store.append_record(
        kind="manual_override",
        namespace="personal",
        source={"agent": "manual"},
        payload={"target": "profile", "section": "communication_style", "operation": "upsert", "body": "Be direct."},
    )
    materialize_cluster_memory(config, store)
    assert "hello cluster" in config.observations_path.read_text()
    assert "Generated by Observational Memory Cluster" in config.reflections_path.read_text()
    assert "Be direct." in config.profile_path.read_text()

    store.append_record(
        kind="tombstone",
        namespace="personal",
        source={"agent": "manual"},
        payload={"target_record_id": observation.record_id, "reason": "test"},
    )
    store.append_record(
        kind="tombstone",
        namespace="personal",
        source={"agent": "manual"},
        payload={"target_record_id": override.record_id, "reason": "test"},
    )
    materialize_cluster_memory(config, store)
    assert "hello cluster" not in config.observations_path.read_text()
    assert "Be direct." not in config.profile_path.read_text()
