"""Transport abstraction for moving encrypted cluster records."""

from __future__ import annotations

from typing import Protocol


class SyncTransport(Protocol):
    name: str

    def list_heads(self, cluster_id: str) -> dict[str, int]: ...

    def read_head(self, cluster_id: str, node_id: str) -> dict | None: ...

    def publish_head(self, cluster_id: str, node_id: str, head: dict) -> None: ...

    def publish_node(self, cluster_id: str, node_id: str, data: bytes) -> None: ...

    def list_nodes(self, cluster_id: str) -> set[str]: ...

    def fetch_node(self, cluster_id: str, node_id: str) -> bytes | None: ...

    def publish_join_request(self, cluster_id: str, request_id: str, data: bytes) -> None: ...

    def list_join_requests(self, cluster_id: str) -> set[str]: ...

    def fetch_join_request(self, cluster_id: str, request_id: str) -> bytes | None: ...

    def publish_join_approval(self, cluster_id: str, request_id: str, data: bytes) -> None: ...

    def fetch_join_approval(self, cluster_id: str, request_id: str) -> bytes | None: ...

    def list_record_ids(self, cluster_id: str, node_id: str) -> set[str]: ...

    def push_record(self, cluster_id: str, node_id: str, record_id: str, data: bytes) -> None: ...

    def fetch_record(self, cluster_id: str, node_id: str, record_id: str) -> bytes | None: ...
